name: 'Build OPAE'
desciption: 'Build OPAE'
inputs:
  branch:
    desciption: branch to checkout
    required: false
    default: 'master'
  build-type:
    desciption: cmake build type
    required: false
    default: 'Release'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.branch }}
    - ${{ inputs.build-type }}
