on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: r-rojo/fedora-rpm@v6
        with:
          branch: master
          build-type: Release
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
